DELETE from VOTE;

DELETE from USER_ROLE;

DELETE from USERS;
ALTER TABLE USERS ALTER COLUMN ID RESTART WITH 1;

INSERT INTO USERS (EMAIL, FIRST_NAME, LAST_NAME, PASSWORD)
VALUES ('user@gmail.com', 'User_First', 'User_Last', '{bcrypt}$2a$10$5OU8ISWS4OrOatYozhXeCuihssYs/ZBsQ9sgUtma6CMBd.h7SXcD.'),
       ('admin@javaops.ru', 'Admin_First', 'Admin_last', '{bcrypt}$2a$10$MTMrh7X8UslRu2Dq5srro.d7oBjJQDz7b66xjViVyxsRwh4y0YCb.');

INSERT INTO USER_ROLE (ROLE, USER_ID)
VALUES ('USER', 1),
       ('ADMIN', 2),
       ('USER', 2);

DELETE FROM RESTAURANT;
ALTER TABLE RESTAURANT ALTER COLUMN ID RESTART WITH 1;

DELETE from DISH;
ALTER TABLE DISH ALTER COLUMN ID RESTART WITH 1;

DELETE from MENU;